import Head from 'next/head';
import { useRouter } from "next/router";
import { CollectionView } from '../../components/collection-view/collection-view';
import { MainSlot } from "../../layouts/main-slot";


export default function Collection() {
  const router = useRouter();
  const slug = router.query.slug as string;

  return (
    <div>
      <Head>
        <title>Twittens - Find your twitter frens</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-100 h-full">
        <MainSlot>
          <CollectionView slug={slug} />
        </MainSlot>
      </div>
    </div>
  );
}