import Head from "next/head";
import { MainSlot } from "../layouts/main-slot";
import { Faq } from "../components/faq/faq";

export default function FaqPage() {


  return (
    <div>
      <Head>
        <title>FAQ | Twittens.xyz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainSlot>
        <Faq />
      </MainSlot>
    </div>
  );
}