import Head from 'next/head';
import { MainSlot } from '../layouts/main-slot';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-100 h-full">

        <MainSlot />
      </div>
    </div>
  );
}
