import Head from 'next/head';
import { CollectionList } from '../components/collection-list/collection-list';
import { MainSlot } from '../layouts/main-slot';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twittens - Find your twitter frens</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainSlot>
        <CollectionList />
      </MainSlot>
    </div>
  );
}
