export const FEATURE_FLAGS = {
  ENABLE_SIDEBAR: true,
  ENABLE_LEADERBOARD: true,
  ENABLE_FEATURE_SECTION_HOMEPAGE: true,
  ENABLE_PAID_LISTING: false,
  ENABLE_FOLLOW_USERS: true,
  ENABLE_LENSENS_IN_MENU: false
};
